/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import RMI.IEstacao;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author cce-teste11
 */
public class InfoCuriosidadesViewInternal extends javax.swing.JInternalFrame {

    /**
     * Creates new form InfoCuriosidadesInternal
     */
    
    public InfoCuriosidadesViewInternal() {
        initComponents();
        this.setLocation(630, 200);
        try {
            TextAreaInfo.setText(MenuView.estacao.getEstacao().getInfo());
        } catch (RemoteException ex) {
            Logger.getLogger(InfoCuriosidadesViewInternal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    //singleton
    private static InfoCuriosidadesViewInternal instancia;

    //singleton
    public static InfoCuriosidadesViewInternal getInstance() {
        //nenhuma instancia foi criada ainda
        if (instancia == null) {
            //cria uma nova instancia do form
            instancia = new InfoCuriosidadesViewInternal();
        }

        //retorna a instancia do form
        return instancia;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextAreaInfo = new javax.swing.JTextArea();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Informações e Curiosidades da Estação São Caetano do Sul");

        TextAreaInfo.setEditable(false);
        TextAreaInfo.setColumns(20);
        TextAreaInfo.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        TextAreaInfo.setLineWrap(true);
        TextAreaInfo.setRows(8);
        TextAreaInfo.setText("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa");
        jScrollPane1.setViewportView(TextAreaInfo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TextAreaInfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
