/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import RMI.IEstacao;
import static View.EstacaoViewFrame.estacao;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;

/**
 *
 * @author cce-teste11
 */
public class MenuView extends javax.swing.JFrame {

    /**
     * Creates new form MenuView
     */
    
    public static IEstacao estacao;
    
    public MenuView() {
        initComponents();
        MenuLinhasActionPerformed(null);        
        MenuPrecoHorarioActionPerformed(null);
        MenuInfoActionPerformed(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        LabelImage = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuLinhas = new javax.swing.JMenuItem();
        MenuInfo = new javax.swing.JMenuItem();
        MenuPrecoHorario = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        LabelImage.setText("jLabel1");
        desktopPane.add(LabelImage);
        LabelImage.setBounds(20, 60, 768, 681);

        jMenu1.setText("Menu");

        MenuLinhas.setText("Linhas disponíveis");
        MenuLinhas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuLinhasActionPerformed(evt);
            }
        });
        jMenu1.add(MenuLinhas);

        MenuInfo.setText("Informações e curiosidades");
        MenuInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuInfoActionPerformed(evt);
            }
        });
        jMenu1.add(MenuInfo);

        MenuPrecoHorario.setText("Preço e horários");
        MenuPrecoHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPrecoHorarioActionPerformed(evt);
            }
        });
        jMenu1.add(MenuPrecoHorario);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        BufferedImage bi = null;
        BufferedImage bi2 = null;
        try {
            bi = ImageIO.read(new File(this.getClass().getResource("mapa.png").toURI()));
            //bi2 = ImageIO.read(new File(this.getClass().getResource("LINHAS-DE-ÔNIBUS-EM-SÃO-CAETANO-DO-SUL.jpg").toURI()));
        } catch (URISyntaxException ex) {
            Logger.getLogger(MenuView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MenuView.class.getName()).log(Level.SEVERE, null, ex);
        }
        LabelImage.setIcon(new ImageIcon(bi.getScaledInstance(LabelImage.getWidth(),LabelImage.getHeight(), Image.SCALE_DEFAULT)));
        //LabelImage2.setIcon(new ImageIcon(bi2.getScaledInstance(LabelImage2.getWidth(),LabelImage2.getHeight(), Image.SCALE_DEFAULT)));
        LabelImage.setLocation(300, 5);
        //LabelImage2.setLocation(750, 0);
    }//GEN-LAST:event_formWindowOpened

    private void MenuLinhasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuLinhasActionPerformed
        EstacaoViewInternal formulario = EstacaoViewInternal.getInstance();
        for(JInternalFrame f : desktopPane.getAllFrames()) {
            if(f.equals(formulario)) {
                formulario.setVisible(true);
                return;
            }
        }
        desktopPane.add(formulario);
        formulario.setVisible(true);
    }//GEN-LAST:event_MenuLinhasActionPerformed

    private void MenuPrecoHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPrecoHorarioActionPerformed
        PrecoHorarioViewInternal formulario = PrecoHorarioViewInternal.getInstance();
        for(JInternalFrame f : desktopPane.getAllFrames()) {
            if(f.equals(formulario)) {
                formulario.setVisible(true);
                return;
            }
        }
        desktopPane.add(formulario);
        formulario.setVisible(true);
    }//GEN-LAST:event_MenuPrecoHorarioActionPerformed

    private void MenuInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuInfoActionPerformed
        InfoCuriosidadesViewInternal formulario = InfoCuriosidadesViewInternal.getInstance();
        for(JInternalFrame f : desktopPane.getAllFrames()) {
            if(f.equals(formulario)) {
                formulario.setVisible(true);
                return;
            }
        }
        desktopPane.add(formulario);
        formulario.setVisible(true);
    }//GEN-LAST:event_MenuInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuView().setVisible(true);
            }
        });
    }
    
    public static void main(IEstacao e) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstacaoViewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstacaoViewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstacaoViewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstacaoViewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        estacao = e;
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelImage;
    private javax.swing.JMenuItem MenuInfo;
    private javax.swing.JMenuItem MenuLinhas;
    private javax.swing.JMenuItem MenuPrecoHorario;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
